version: "3"
services:
  pipelines: # Pipelines
    image: swiri021/snakemake-gui-controller:v1.0.2
    # Change volumes to your path
    # /your-git-clone-folder/snakemake-gui-controller/pipelines:/pipeline_controller/pipelines
    volumes:
      - /Users/junheeyoon/Desktop/OpenKBC/snakemake-gui-controller/pipelines:/pipeline_controller/pipelines
    ports:
      - 80:5000
    depends_on:
      - redis
    working_dir: /pipeline_controller
    command: conda run -n pipeline_controller_base gunicorn --bind 0.0.0.0:5000 --workers 2 --threads 4 --worker-class gthread connector:app
    #command: tail -f /dev/null (Testing purpose)
    container_name: snakemakeController

  redis: # redis
    image: redis:alpine
    command: redis-server
    ports:
      - 6379:6379
    container_name: scRedisServer

  celery: # celery
    image: swiri021/snakemake-gui-controller:v1.0.2
    # Change volumes to your path
    # /your-git-clone-folder/snakemake-gui-controller/pipelines:/pipeline_controller/pipelines
    volumes:
      - /Users/junheeyoon/Desktop/OpenKBC/snakemake-gui-controller/pipelines:/pipeline_controller/pipelines
    deploy:
      resources:
        limits:
          memory: 8000m
    working_dir: /pipeline_controller
    command: conda run -n pipeline_controller_base celery -A app.celery worker --loglevel=info
    #command: tail -f /dev/null (Testing purpose)
    depends_on:
      - redis
      - pipelines
    container_name: scCeleryContainer